// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://firbkkdadxfykzdtbnfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcmJra2RhZHhmeWt6ZHRibmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjQyNzksImV4cCI6MjA3NDQ0MDI3OX0.Ttk2HRpKj3Un-SC2brykSBRL6kD3xfds-H2tuaXTRGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});